remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: A Semester of Multimodal Work: Chase's Digital Portfolio
description: Bookmark this to keep an eye on my project updates!
